### ISSUE TITLE
Mastodon Support

### ISSUE THREAD

**Issue by meskarune** [amuza/birdie#203]
Would it be possible to add support for mastodon? It is a federated FOSS alternative to twitter: https://joinmastodon.org/

The API documentation is here: https://github.com/tootsuite/documentation/blob/master/Using-the-API/API.md

**Comment by baimafeima** [comment]
I absolutely second this. Would be great to have Mastodon Support.

**Comment by ivonunes** [comment]
Unfortunately this is out of scope for Birdie - we’ve chosen not to support additional services and prefer to focus on providing a great Twitter experience. We’ll reopen this issue if this ever changes in the future.

**Comment by rodneyrod** [comment]
There's another Elementary OS project doing exactly that:
https://github.com/bleakgrey/tootle

The only problem is that you need two separate apps to have both Twitter and Mastodon and is not a use case that is useful to me.
