### ISSUE TITLE
Birdie does not show the icon in a notification

### ISSUE THREAD

**Issue by alainm23** [amuza/birdie#207]
Thank you for continuing with the development of Birdie.
Each time a notification is sent, the icon is not displayed
![captura de pantalla de 2018-04-29 04-44-28](https://user-images.githubusercontent.com/33765137/39405282-1d63ad8e-4b68-11e8-84d7-64553b8e3c22.png)

**Comment by ivonunes** [comment]
Thanks for reporting this issue. This should be resolved now :)
